### PR TITLE
WIP: Pkg Artifacts with legacy mode

### PR DESCRIPTION
**Pull request by benlorenz**
**This is still work in progress**

Switch to Pkg Artifacts for dependencies with a legacy mode for Julia 1.0 - 1.2.
Legacy mode is using a generated build_flint.jl which uses the tarballs from the artifacts.
To use the artifacts one has to add the [OscarRegistry](https://github.com/oscar-system/OscarRegistry).

I have removed the source build as in #3, for now I have only added a FLINT_PATH environment variable to specify custom `libflint.$dlext` for julia 1.2 or older.
For julia 1.3 one can add the following to `~/.julia/artifacts/Overrides.toml`:
```
[cabf4574-4f87-5802-9a0b-e4b5b01a80fc]
flint = "/home/me/flint-install"
```
where `/home/me/flint-install` should contain a `lib` directory containing `libflint.so`

I removed the setting of gmp memory functions. I dont think we should touch this, also julia is doing this by itself already and we should be using the julia-libgmp.

I added a small ccall test using `flint_malloc` and `flint_free`.

Issues / Todo:
- [x] multiple libgmp seems to cause no issues.
- [x] Add flint_jll to Yggdrasil.
- [x] update yggdrasil flint
- [ ] Better integration of source build.
- [x] More testing of different configurations / julia versions: tests on travis seem good (as expected) so far
- [x] reverse dependency tests
- and probably more

### CODE REVIEW

**Comment by fieker** [comment]
We're only setting the gmp functions in the unlikely event of having to load gmp ourselves. If gmp is already there, the memory functions are not touched. (This assumes that Julia is doing it)

**Comment by fingolfin** [comment]
There is now a Flint_jll (see https://github.com/JuliaPackaging/Yggdrasil/pull/661) thanks to @benlorenz , yay!

**Comment by fingolfin** [comment]
So, how important is support for Julia 1.0-1.2 to us? We can't support them in Oscar.jl anyway, because Gap.jl needs Julia 1.1 at the least (and I've gone full in with 1.3 otherwise since we declared elsewhere that'll be the minimum for Oscar overall).

I mean, I don't mind adding in backwards compatibility shims if that helps (and somebody else does it ;-) ), I just wonder if it's really worth the effort?

**Comment by fieker** [comment]
On Fri, Apr 03, 2020 at 05:53:04PM -0700, Max Horn wrote:
> So, how important is support for Julia 1.0-1.2 to us? We can't support them in Oscar.jl anyway, because Gap.jl needs Julia 1.1 at the least (and I've gone full in with 1.3 otherwise since we declared elsewhere that'll be the minimum for Oscar overall).
> 
> I mean, I don't mind adding in backwards compatibility shims if that
> helps (and somebody else does it ;-) ), I just wonder if it's really
> worth the effort? 
> 
Bill will kill anyone if Nemo is no-longer running in 1.0 unneccessary.
Oscar is 1.3 and above, but as long as Nemo is independently useful,
this will be difficult to argue....

What are the advantages to us of using the flint_jll at this point over
the binary builder?

**Comment by fingolfin** [comment]
The main reason I am wondering is that using `GMP_jll` and `Zlib_jll` is considerably more convenient for me than using their "old-style" binary builder counterparts; yet I am afraid that mixing the two will again trigger the warning in LoadFlint about multiple GMP being loaded... For this reason, I also think we should disable that error. It's OK for Flint, but for GMP, it just is quite likely that this will be triggered eventually by other packages outside our control.

**Comment by benlorenz** [comment]
At the moment it seems that with `using GMP_jll` (even without mixing with old style build.jl) there will always be two gmp libraries loaded, one from julia and one from the artifact. We could get rid of the second one for some packages by changing GMP_jll from a dependency to a build-dependency. But for all packages that need some compilation in build.jl (or even at runtime) we need GMP_jll for the gmp headers.

And just to be clear: the jll packages are what BinaryBuilder now produces, and BinaryProvider (which is used for he build_*.jl files) will be deprecated at some point.
See also here: https://github.com/JuliaPackaging/Yggdrasil/issues/653

**Comment by fieker** [comment]
On Sat, Apr 04, 2020 at 02:53:17AM -0700, Max Horn wrote:
> The main reason I am wondering is that using `GMP_jll` and `Zlib_jll`
> is considerably more convenient for me than using their "old-style"
> binary builder counterparts; yet I am afraid that mixing the two will
> again trigger the warning in LoadFlint about multiple GMP being
> loaded... For this reason, I also think we should disable that error.
> It's OK for Flint, but for GMP, it just is quite likely that this will
> be triggered eventually by other packages outside our control.
> 
The problem is that, once we have multiple gmp, the system is from our
point of view non-deterministic and will crash - unless all gmps are
 - binary compatible
 - using compatible allocaters
The crashing code is always an idirect call to gmp. flint -> gmp
While I can control the flint that I get (setting absolute path names) I
cannot control which gmp flint is using. As far as I can say not even
that subsequent calls to different flint functions will call the same
gmp all the time. This is likely to be the case, and might be able to
be enforced by some flags to dlopen, but I don't know.

At this point, having multiple gmps means that I can no longer guarantee
that pairs of alloc/free will be resolved in the same library using the
same underlying memory manager. Possibly there are other, better means
to enforce this, but I don't know how.

A slightly different solution we might try - also awkward - is to patch
flint to use the gmp allocators:
  flint_set_memory_functions_to_gmp()
and hope that within flint all calls are resolved to the same gmp...

Even worse we have more complicated c-graphs
  libantic -> gmp
           -> flint -> gmp
                    -> mpfr -> gmp
  arb  -> gmp
  mpfr -> gmp

and those gmp should line up...

**Comment by fieker** [comment]
On Sat, Apr 04, 2020 at 02:53:17AM -0700, Max Horn wrote:
> The main reason I am wondering is that using `GMP_jll` and `Zlib_jll`
> is considerably more convenient for me than using their "old-style"
> binary builder counterparts; yet I am afraid that mixing the two will
> again trigger the warning in LoadFlint about multiple GMP being
> loaded... For this reason, I also think we should disable that error.
> It's OK for Flint, but for GMP, it just is quite likely that this will
> be triggered eventually by other packages outside our control.
> 

I don't mind giving up in 1.0, for Oscar we're already past that
decision. But as long as Nemo is independent and Julia does not commit
to a new LTS we're screwed

**Comment by fingolfin** [comment]
Sure, I am fine with using the old-style BinaryBuilder / BinaryProvider stuff here, resp. keep compatibility with Julia 1.0, if that's necessary for Nemo / to make Bill happy ;-).

As to multiple GMP versions being loaded: My point is that we can't prevent that anyway: if `LoadFlint` is loaded first then it doesn't see if a dozen copies of libgmp get loaded afterwards. There are Julia package using `GMP_jll` already anyway, and people may load them after Oscar...

In the meantime, the check causes an annoyance to people who would otherwise be happily using our stuff. So I would suggest that we downgrade it to a (big and fat) warning in the meantime... Independent of that, I'll work on fixing GAP.jl to not load a new GMP (it's going to be a bit slow today without the babysitter, but I'll manage ;-) )

**Comment by fieker** [comment]
On Mon, Apr 06, 2020 at 01:36:20AM -0700, Max Horn wrote:
> Sure, I am fine with using the old-style BinaryBuilder /
> BinaryProvider stuff here, resp. keep compatibility with Julia 1.0, if
> that's necessary for Nemo / to make Bill happy ;-).
> 
> As to multiple GMP versions being loaded: My point is that we can't
> prevent that anyway: if `LoadFlint` is loaded first then it doesn't
> see if a dozen copies of libgmp get loaded afterwards. There are Julia
> package using `GMP_jll` already anyway, and people may load them after
> Oscar...
LoadFlint will, currently, neer actually load gmp as it is already
present...
I see your point and maybe that is s.th. we need to into an issue for
Julia: having multiple copies of any library and non-julia dependencies
between packages is dangerous.
> 
> In the meantime, the check causes an annoyance to people who would
> otherwise be happily using our stuff. So I would suggest that we
> downgrade it to a (big and fat) warning in the meantime... Independent
Sure - however, it will produce random crashes...
As long as it is clear that we cannot help others that is fine.

> of that, I'll work on fixing GAP.jl to not load a new GMP (it's going
> to be a bit slow today without the babysitter, but I'll manage ;-) )
All the best!

**Comment by fieker** [comment]
I've just pushed and replaced the error by @warn

**Comment by fingolfin** [comment]
Overall, I like this PR: It allows us to use `_Jll` packages while retaining compatibility with Julia 1.0-1.2, so I'd hope @wbhart has no objects to it.

@benlorenz What needs to be done with this PR to make it ready, from your perspective? The one thing I found by re-reading the discussion is that `GMP_jll.jl` will always load a second copy of GMP... But apparently this causes no issues in practice (as otherwise I am sure others would have noticed, and also our tests).

I am really interested in getting this in, as it would allow GAP.jl and Polymake.jl to switch to Jll packages, which will simplify all kinds of things down the road, I think.

**Comment by benlorenz** [comment]
I think the second gmp from GMP_jll should not cause issues. At some point this might be resolved by julia itself using pkg artifacts for dependencies.

I need to test the latest version with older julia versions again and check what downstream software needs in form of exported variables (libgmp path, libflint path, ..., maybe handles instead?)

Also I wanted to provide a function for running the old build script manually which at the end shows what is needed to use the custom installation.

I got distracted by trying to update polymake for the artifacts.

**Comment by fingolfin** [comment]
Note that we use Travis to test this package against Julia 1.0, 1.3, 1.4 and nightly, on Linux and macOS. we can also add a test using Xcode 11.4; and we only dropped 1.1 and 1.2 to reduce the time the tests run, but we can of course add them back (this repo shouldn't get updates too often anyway).

Anyway, no pressure, we all are busy with many other things, too :-). I just got reminded of this because of https://github.com/oscar-system/GAP.jl/issues/415 :-). Thank you for working on this.

**Comment by benlorenz** [comment]
I have switched this back to the FLINT_jll from before 2.6 which was tagged as 0.0.1 in Yggdrasil. This is compatible with the current Nemo release and the also the latest polymake release.
I have added reverse dependency tests in travis building and testing Nemo and Polymake (and both together) with the current LoadFlint version. This takes quite a while but should cover all relevant platforms: https://travis-ci.com/github/oscar-system/LoadFlint.jl/builds/172498061
What is not currently tested on travis is using the custom flint path or overrides.

We can do the bump to 2.6 in a later pull request together with a version bump to 0.2.0 when Nemo is fixed to work with 2.6 (or can work with both flint versions).

**Comment by thofma** [comment]
Thanks Benjamin. How about merging your PR and tagging it as 0.2.0? Then we can play with it on the Nemo side (without automatically using it) and see if everything works fine. I know that the reverse dependency tests should catch any such error, but I want to make sure :)

**Comment by fingolfin** [comment]
Note that both Polymake.jl and Nemo.jl currently only use LoadFlint 0.1, so they won't see or use 0.2.0...

So what is the plan forward here? To update Nemo.jl and Polymake.jl to use LoadFlint.jl 0.2.0? Then release LoadFlint 0.3.0 which uses FLINT_jll 2.6.0 (which will of course not be able to pass the "reverse" tests), then afterwards update Nemo.jl and Polymake.jl once more.

(BTW, all these issue would be easy to resolve if we were using a monorepo ... :-)

**Comment by thofma** [comment]
Yes. We should actually use something newer then 2.6.0. There has been some important bugfixes since then.

Nemo is basically good to go with Artifacts and legacy mode, see https://github.com/Nemocas/Nemo.jl/pull/845.

**Pull request merged**
