### PR TITLE
add CI github actions and remove .travis.yml

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by thofma** [comment]
We had some special tests here in the .travis.yml. Could you try to convert them? Here is an example to run custom commands using github actions: https://github.com/thofma/Hecke.jl/blob/master/.github/workflows/CILong.yml.

**Comment by rfourquet** [comment]
Ok, I tried to port the tests, it seems to "work" but the tests fail at the same place in "Nemo/test/generic/Matrix-test.jl:94"... was this failure seen somewhere else?

I didn't replicate the exact same logic for short vs long revdeps, I thought it didn't matter too much, but I can update. I think we don'e test on windows in Nemo etc., should we test LoadFLing on windows?

**Comment by rfourquet** [comment]
Ok, I can actually reproduce the failure locally. Trying now to understand more the conditions for it to happen.

**Comment by thofma** [comment]
I think we test Nemo on Windows. Don't think we need it here.

I don't know about those 1.5 errors. Seems to be related to polymake. Maybe @benlorenz knows more?

**Comment by benlorenz** [comment]
The error is that polymake picks up the wrong perl binary while trying to compile new C++ wrapper code, I am somewhat surprised that this didn't cause problems earlier.
The initialization of Polymake.jl should probably add the path of the Perl_jll artifact to the beginning of the PATH variable instead of the end, to make sure that the correct `perl` binary is used. I will create a pull request for Polymake.jl and create a new release soon. (Unfortunately we cannot put the correct path directly into polymake_jll as we don't know it at build-time)

**Comment by thofma** [comment]
Thanks for having a look.

**Pull request merged**
