### PR TITLE
Remove the source build option

### PR DESCRIPTION
**Pull request by fingolfin**
- it was never tested, and in fact broken
- no end user should ever (have to) use it
- if a developer wants to use a custom flint version, then they can
  achieve this by using the Artifact override system, see
  <https://julialang.github.io/Pkg.jl/dev/artifacts/#Overriding-artifact-locations-1>

### CODE REVIEW

**Comment by fieker** [comment]
While I am happy to remove this (for a different reason), I thought
artifacts exist only in Julia 1.3 and up, hence not in 1.0
Nemo will have to work in 1.0 for the forseeable future..

**Comment by benlorenz** [comment]
We could also add a FLINT_PATH variable for older julia version to override the BinaryBuilder flint. I think this is better than having a source build in the build.jl.

I will try to create a (draft) pull request for using the pkg artifacts with a legacy mode for older julia versions later today.

**Comment by fieker** [comment]
On Wed, Mar 25, 2020 at 03:56:55AM -0700, Benjamin Lorenz wrote:
> We could also add a FLINT_PATH variable for older julia version to override the BinaryBuilder flint. I think this is better than having a source build in the build.jl.
> 
> I will try to create a (draft) pull request for using the pkg artifacts with a legacy mode for older julia versions later today.
> 
Great!

But from mz point of view, the "cleaning up" and "beautification" is
secondary..

**Comment by wbhart** [comment]
Note that I use a source build of Flint all the time. I hope this will not become more complicated.

**Comment by fieker** [comment]
On Wed, Mar 25, 2020 at 09:06:32AM -0700, wbhart wrote:
> Note that I use a source build of Flint all the time. I hope this will not become more complicated.
> 
So do I...
Benjamin Lorenz is looking into this, nd it appears it might be easier
as the flint can be located anywhere

**Comment by wbhart** [comment]
I hope that you will consider that at present the RPATH's are set by the Nemo build script. It's not Flint that is the concern, but its dependencies.

**Comment by fieker** [comment]
On Wed, Mar 25, 2020 at 11:30:38AM -0700, wbhart wrote:
> I hope that you will consider that at present the RPATH's are set by the Nemo build script. It's not Flint that is the concern, but its dependencies.
At this point it passes all tests.
On all architectures.
The source build is a different problem that we will address.
My impression from Benjamin is, that it is easier (will be easier) as it
is decoupled from the build.jl

Currently, in Oscar, and the Nemo + Polymake tests we're using Julia's
gmp and julia's mpfr
and all seems to be fine.

**Comment by fieker** [comment]
On Wed, Mar 25, 2020 at 11:30:38AM -0700, wbhart wrote:
> I hope that you will consider that at present the RPATH's are set by the Nemo build script. It's not Flint that is the concern, but its dependencies.
> 
I'm not saying there are no problems, but none have emerged so far.
Do you have found any?

**Pull request closed without merging**
